### PR TITLE
Macro client.0.0.1

### PR DESCRIPTION
**Pull request by frickler24**
Hi,
as I wrote in the forum, the last days I worked on a macro handling for the K95 (and maybe other keyboards, I don't know). Now the first version is IMHO ready for testing.

### CODE REVIEW

**Comment by RattyDAVE** [comment]
Hi,

Thank you very much.

I have a K95 RGB and an M65 RGB.

With ONLY the K95 plugged in the keyboard works. (not fully tested but I get lights and no problems found as of yet.)

With the K95 and M65 in. Well. This is where is fails. Keyboard goes On and Off and with the mouse. So both the mouse and keyboard are unuseable.

Dave

**Comment by frickler24** [comment]
@RattyDAVE thanks for the feedback. Does anyone else have problems with this configuration? Or in other combinations KB + mouse?

**Comment by ccMSC** [comment]
Hey, it may be a while before I have a chance to look over this, but I just wanted to let you know that I've seen it :)

I'll merge it into the testing branch sometime in the next 1-2 weeks.

**Comment by frickler24** [comment]
OK, pls don't hurry.

**Pull request closed without merging**
