### PR TITLE
Macro client.0.0.2

### PR DESCRIPTION
**Pull request by frickler24**
Hi ccMSC, 
today I did an addition to the "More settings" tab. The extension is useful only with the 0e5aac4 and 
adds a ckeckbox for the short uspleep-calls, we diskussed earlier in issue #217.

### CODE REVIEW

**Comment by RattyDAVE** [comment]
Thank you again. 

Just tried as before. 

I have a K95 RGB and an M65 RGB.

With ONLY the K95 plugged in the keyboard works. (not fully tested but I get lights and no problems found as of yet.)

With the K95 and M65 in. Well. This is where is fails. Keyboard goes On and Off and with the mouse. So both the mouse and keyboard are unusable.

**Comment by chrisgogreen** [comment]
Why do you have two keyboards at the same time? That is a new use case for me.

**Comment by RattyDAVE** [comment]
K95 RGB (Keyboard) - http://www.corsair.com/en-gb/landing/k95-rgb
M65 RGB (Mouse) - http://www.corsair.com/en-gb/landing/m65-rgb

**Comment by frickler24** [comment]
@RattyDAVE Hello, it took some time because I had no M65 until yesterday...
Now I fixed a bug, which should be the reason for the "blinking" effect you described.
The client sent a "macro clear" command to the daemon for each device.
Because that's senseless for the mouse, there is no corresponding function handler for it
and the daemon got a SIGSEGV.
Depending on how your system restarts a killed daemon, there might be that blinker.
On my Mint 17.2 I got a different effect - the daemon restarted, the mouse was fine and the KB dead.
Anyway - that bug is fixed in my newest branch macro-client.0.0.2 : dd5ae11 and KB + mouse are running fine.
pls feel free to retest it.

@ccMSC pls merge the dd5ae11 instead of the older versions.
Should I give you a new pull request for that?

**Comment by RattyDAVE** [comment]
Ill give that a shot later today!

BTW I am running Mint 17.2 too.

**Comment by RattyDAVE** [comment]
@frickler24 Works perfect now. I can now have key presses assigned to keys.

Thanks very much.

**Comment by frickler24** [comment]
@RattyDAVE Thank you for testing!

**Comment by ccMSC** [comment]
Hi, sorry for taking so long to get to this! I just tested it out, everything seems to be working great.

Two requests:
1) Could you rebase this against the regular `testing` branch, as opposed to `newfx`? I'm not ready to merge the effects just yet.
2) Please re-open the request with the mouse fix incoporated.

Thanks for your work!

**Comment by frickler24** [comment]
@ccMSC OK, I will need some days. Too busy in the office...
Maybe that I need some help for rebasing, because it is my first git project on github.

**Comment by ccMSC** [comment]
I think what you want is called a "cherry pick", which allows you to take the changes from one branch to another without all of the baggage.

**Comment by frickler24** [comment]
Tnx fpr the tip, I've found a good description about cherry picking. Hope on weekend i'll get it done.

**Pull request closed without merging**
