### PR TITLE
Fn key binding fix for Strafe

### PR DESCRIPTION
**Pull request by SicVolo**
@ccMSC the UI is fixed but the Fn key does not seem call other functions after a re-bind. I got its USB trace and it does not seem to work like every modifier - it only sends HID 2 packets, not 4. I don't have a good grasp of HID, can you please look at this capture - http://pastebin.com/qydST3Bw and tell me how it could be fixed or if it's indeed possible. The capture is what happens on the USB bus when I press "Fn" on Strafe.

### CODE REVIEW

**Comment by SicVolo** [comment]
@ccMSC thanks, any ideas on why Fn does not invoke an new action after it's been re-bound?

**Comment by ccMSC** [comment]
The 64-byte packet is a bitfield which contains each pressed key. The driver copies them directly into the input field, which is where the ordering in `keymap.c` comes from. If I've counted correctly, the Fn key is at position 146, which puts it three bits past G18. I've modified the keymap so it should actually register the keypress now.

There's also supposed to be a standard USBHID packet for each key, but according to your capture, it's empty. I guess Corsair just didn't want to mess with that. It doesn't matter anyway, since the driver relies on the proprietary input when the keyboard is under software control.

**Comment by SicVolo** [comment]
Awesome, thank you! I guessed the keymap.c order was relevant, but I could not figure how it was relevant or where it was used.

**Comment by ccMSC** [comment]
@SicVolo I forgot to ask, but do the Fn-based media keys work when the driver is active, or do they just register `F5`-`F12`? I'm curious whether the hardware is remapping them, or if it expects the software to handle that.

**Comment by SicVolo** [comment]
They work even if CKB is down, so it must be a hardware remap.

**Comment by ccMSC** [comment]
Thought so. I imagine some people will want to use a different key to activate them, but if it's all hardware based then there's nothing we can do about that. Good to have the key itself rebindable anyway.

**Pull request merged**
